/*
 * Copyright 2023 Slawomir Czerwinski
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

{
  parserClass="it.czerwinski.ide.plugins.valve.lang.parser.VdfParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Vdf"
  psiImplClassSuffix="Impl"
  psiPackage="it.czerwinski.ide.plugins.valve.lang.psi"
  psiImplPackage="it.czerwinski.ide.plugins.valve.lang.psi.impl"

  elementTypeHolderClass="it.czerwinski.ide.plugins.valve.lang.psi.VdfTypes"
  elementTypeClass="it.czerwinski.ide.plugins.valve.lang.psi.VdfElementType"
  tokenTypeClass="it.czerwinski.ide.plugins.valve.lang.psi.VdfTokenType"

  tokens = [
    LBRACE='{'
    RBRACE='}'
    COMMENT='regexp://.*'
    STRING="regexp:\"([^\\\"\r\n]|\\[^\r\n])*\"?"
  ]

  extends("object|literal")=value
  implements("property")=[
    "it.czerwinski.ide.plugins.valve.lang.psi.VdfElement"
    "com.intellij.psi.PsiNamedElement"
  ]
}

vdf ::= property

property ::= key value {
  mixin="it.czerwinski.ide.plugins.valve.lang.psi.impl.VdfPropertyMixin"
}

key ::= STRING {
  implements="it.czerwinski.ide.plugins.valve.lang.psi.VdfStringHolder"
}

value ::= object | literal

object ::= LBRACE property* RBRACE

literal ::= STRING {
  implements="it.czerwinski.ide.plugins.valve.lang.psi.VdfStringHolder"
}
